name: no_return_traker
description: "A chat-based game."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  blinking_text: ^1.0.4
  shared_preferences: ^2.0.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  audioplayers: ^5.2.1
  flutter_launcher_icons: ^0.13.1
  google_mobile_ads: ^5.2.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.0.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:

  - assets/drawables/start.gif
  - assets/drawables/0.png
  - assets/drawables/0_dark.png
  - assets/drawables/1.png
  - assets/drawables/2.png
  - assets/drawables/recruitment_officer_avatar.png
  - assets/drawables/control_center_avatar.png
  - assets/drawables/alien_avatar.png
  - assets/drawables/echo_avatar.png
  - assets/drawables/survivor_avatar.png

  - assets/drawables/info_screen_alien.png
  - assets/drawables/waiting_screen_analysis.png
  - assets/drawables/waiting_screen_climbing.png
  - assets/drawables/waiting_screen_crossing.png
  - assets/drawables/info_screen_explosion.png
  - assets/drawables/waiting_screen_hibernation.png
  - assets/drawables/waiting_screen_recruitment.png
  - assets/drawables/waiting_screen_starting.png
  - assets/drawables/waiting_screen_returning_to_ship.png

  - assets/drawables/game_over_black_hole.png
  - assets/drawables/game_over_cliff_fall.png
  - assets/drawables/game_over_coldness.png
  - assets/drawables/game_over_crystal_explosion.png
  - assets/drawables/game_over_gas_intoxication.png
  - assets/drawables/game_over_ship_explosion.png
  - assets/drawables/info_screen_crystal_shaking.png

  - assets/database/dialog_nodes_pl.json
  - assets/database/dialog_nodes_en.json

  - assets/sound/background_music.mp3
  - assets/sound/click.mp3
  - assets/sound/click2.mp3


  fonts:
    - family: VT323
      fonts:
        - asset: assets/fonts/VT323.ttf


    - family: mnc
      fonts:
      - asset: assets/fonts/mnc.ttf

